### ISSUE TITLE
Controllo iniziale variabili d'ambiente

### ISSUE THREAD

**Issue by AndreFra96** [AndreFra96/strava-tools#10]
Per evitare di dover controllare ogni volta che utilizziamo una variabile d'ambiente che essa sia presente inseriamo una controllo iniziale.

Il controllo deve essere effettuato nel momento in cui viene avviata l'applicazione.

**Comment by AndreFra96** [comment]
@rafaelventura204 
Ho visto che con Next.js non esiste un metodo di default per eseguire del codice prima di lanciare l'applicazione.

Comunque ci sono alcuni modi per aggirare questo problema, quello che vorrei usare è [questo](https://github.com/vercel/next.js/discussions/15341#discussioncomment-5845714)

Appena riesco apro un nuovo branch, poi dagli un'occhiata.

**Comment by AndreFra96** [comment]
@rafaelventura204 ho creato il branch, guarda [qui](https://github.com/AndreFra96/strava-tools/commit/09c85a900b4ea2933f969c2e75acd63dee673779)

**Comment by rafaelventura204** [comment]
perfetto, appena posso guardo un attimo tutto!
